// coverage:ignore-file
// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint, unused_import, invalid_annotation_target, unnecessary_import

import 'package:json_annotation/json_annotation.dart';

@JsonEnum()
enum UpdateClientProfileDtoLanguages {
  @JsonValue('aa')
  aa('aa'),
  @JsonValue('ab')
  ab('ab'),
  @JsonValue('ae')
  ae('ae'),
  @JsonValue('af')
  af('af'),
  @JsonValue('ak')
  ak('ak'),
  @JsonValue('am')
  am('am'),
  @JsonValue('an')
  an('an'),
  @JsonValue('ar')
  ar('ar'),

  /// The name has been replaced because it contains a keyword. Original name: `as`.
  @JsonValue('as')
  valueAs('as'),
  @JsonValue('av')
  av('av'),
  @JsonValue('ay')
  ay('ay'),
  @JsonValue('az')
  az('az'),
  @JsonValue('ba')
  ba('ba'),
  @JsonValue('be')
  be('be'),
  @JsonValue('bg')
  bg('bg'),
  @JsonValue('bi')
  bi('bi'),
  @JsonValue('bm')
  bm('bm'),
  @JsonValue('bn')
  bn('bn'),
  @JsonValue('bo')
  bo('bo'),
  @JsonValue('br')
  br('br'),
  @JsonValue('bs')
  bs('bs'),
  @JsonValue('ca')
  ca('ca'),
  @JsonValue('ce')
  ce('ce'),
  @JsonValue('ch')
  ch('ch'),
  @JsonValue('co')
  co('co'),
  @JsonValue('cr')
  cr('cr'),
  @JsonValue('cs')
  cs('cs'),
  @JsonValue('cu')
  cu('cu'),
  @JsonValue('cv')
  cv('cv'),
  @JsonValue('cy')
  cy('cy'),
  @JsonValue('da')
  da('da'),
  @JsonValue('de')
  de('de'),
  @JsonValue('dv')
  dv('dv'),
  @JsonValue('dz')
  dz('dz'),
  @JsonValue('ee')
  ee('ee'),
  @JsonValue('el')
  el('el'),
  @JsonValue('en')
  en('en'),
  @JsonValue('eo')
  eo('eo'),
  @JsonValue('es')
  es('es'),
  @JsonValue('et')
  et('et'),
  @JsonValue('eu')
  eu('eu'),
  @JsonValue('fa')
  fa('fa'),
  @JsonValue('ff')
  ff('ff'),
  @JsonValue('fi')
  fi('fi'),
  @JsonValue('fj')
  fj('fj'),
  @JsonValue('fo')
  fo('fo'),
  @JsonValue('fr')
  fr('fr'),
  @JsonValue('fy')
  fy('fy'),
  @JsonValue('ga')
  ga('ga'),
  @JsonValue('gd')
  gd('gd'),
  @JsonValue('gl')
  gl('gl'),
  @JsonValue('gn')
  gn('gn'),
  @JsonValue('gu')
  gu('gu'),
  @JsonValue('gv')
  gv('gv'),
  @JsonValue('ha')
  ha('ha'),
  @JsonValue('he')
  he('he'),
  @JsonValue('hi')
  hi('hi'),
  @JsonValue('ho')
  ho('ho'),
  @JsonValue('hr')
  hr('hr'),
  @JsonValue('ht')
  ht('ht'),
  @JsonValue('hu')
  hu('hu'),
  @JsonValue('hy')
  hy('hy'),
  @JsonValue('hz')
  hz('hz'),
  @JsonValue('ia')
  ia('ia'),
  @JsonValue('id')
  id('id'),
  @JsonValue('ie')
  ie('ie'),
  @JsonValue('ig')
  ig('ig'),
  @JsonValue('ii')
  ii('ii'),
  @JsonValue('ik')
  ik('ik'),
  @JsonValue('io')
  io('io'),

  /// The name has been replaced because it contains a keyword. Original name: `is`.
  @JsonValue('is')
  valueIs('is'),
  @JsonValue('it')
  it('it'),
  @JsonValue('iu')
  iu('iu'),
  @JsonValue('ja')
  ja('ja'),
  @JsonValue('jv')
  jv('jv'),
  @JsonValue('ka')
  ka('ka'),
  @JsonValue('kg')
  kg('kg'),
  @JsonValue('ki')
  ki('ki'),
  @JsonValue('kj')
  kj('kj'),
  @JsonValue('kk')
  kk('kk'),
  @JsonValue('kl')
  kl('kl'),
  @JsonValue('km')
  km('km'),
  @JsonValue('kn')
  kn('kn'),
  @JsonValue('ko')
  ko('ko'),
  @JsonValue('kr')
  kr('kr'),
  @JsonValue('ks')
  ks('ks'),
  @JsonValue('ku')
  ku('ku'),
  @JsonValue('kv')
  kv('kv'),
  @JsonValue('kw')
  kw('kw'),
  @JsonValue('ky')
  ky('ky'),
  @JsonValue('la')
  la('la'),
  @JsonValue('lb')
  lb('lb'),
  @JsonValue('lg')
  lg('lg'),
  @JsonValue('li')
  li('li'),
  @JsonValue('ln')
  ln('ln'),
  @JsonValue('lo')
  lo('lo'),
  @JsonValue('lt')
  lt('lt'),
  @JsonValue('lu')
  lu('lu'),
  @JsonValue('lv')
  lv('lv'),
  @JsonValue('mg')
  mg('mg'),
  @JsonValue('mh')
  mh('mh'),
  @JsonValue('mi')
  mi('mi'),
  @JsonValue('mk')
  mk('mk'),
  @JsonValue('ml')
  ml('ml'),
  @JsonValue('mn')
  mn('mn'),
  @JsonValue('mr')
  mr('mr'),
  @JsonValue('ms')
  ms('ms'),
  @JsonValue('mt')
  mt('mt'),
  @JsonValue('my')
  my('my'),
  @JsonValue('na')
  na('na'),
  @JsonValue('nb')
  nb('nb'),
  @JsonValue('nd')
  nd('nd'),
  @JsonValue('ne')
  ne('ne'),
  @JsonValue('ng')
  ng('ng'),
  @JsonValue('nl')
  nl('nl'),
  @JsonValue('nn')
  nn('nn'),
  @JsonValue('no')
  no('no'),
  @JsonValue('nr')
  nr('nr'),
  @JsonValue('nv')
  nv('nv'),
  @JsonValue('ny')
  ny('ny'),
  @JsonValue('oc')
  oc('oc'),
  @JsonValue('oj')
  oj('oj'),
  @JsonValue('om')
  om('om'),
  @JsonValue('or')
  or('or'),
  @JsonValue('os')
  os('os'),
  @JsonValue('pa')
  pa('pa'),
  @JsonValue('pi')
  pi('pi'),
  @JsonValue('pl')
  pl('pl'),
  @JsonValue('ps')
  ps('ps'),
  @JsonValue('pt')
  pt('pt'),
  @JsonValue('qu')
  qu('qu'),
  @JsonValue('rm')
  rm('rm'),
  @JsonValue('rn')
  rn('rn'),
  @JsonValue('ro')
  ro('ro'),
  @JsonValue('ru')
  ru('ru'),
  @JsonValue('rw')
  rw('rw'),
  @JsonValue('sa')
  sa('sa'),
  @JsonValue('sc')
  sc('sc'),
  @JsonValue('sd')
  sd('sd'),
  @JsonValue('se')
  se('se'),
  @JsonValue('sg')
  sg('sg'),
  @JsonValue('si')
  si('si'),
  @JsonValue('sk')
  sk('sk'),
  @JsonValue('sl')
  sl('sl'),
  @JsonValue('sm')
  sm('sm'),
  @JsonValue('sn')
  sn('sn'),
  @JsonValue('so')
  so('so'),
  @JsonValue('sq')
  sq('sq'),
  @JsonValue('sr')
  sr('sr'),
  @JsonValue('ss')
  ss('ss'),
  @JsonValue('st')
  st('st'),
  @JsonValue('su')
  su('su'),
  @JsonValue('sv')
  sv('sv'),
  @JsonValue('sw')
  sw('sw'),
  @JsonValue('ta')
  ta('ta'),
  @JsonValue('te')
  te('te'),
  @JsonValue('tg')
  tg('tg'),
  @JsonValue('th')
  th('th'),
  @JsonValue('ti')
  ti('ti'),
  @JsonValue('tk')
  tk('tk'),
  @JsonValue('tl')
  tl('tl'),
  @JsonValue('tn')
  tn('tn'),
  @JsonValue('to')
  to('to'),
  @JsonValue('tr')
  tr('tr'),
  @JsonValue('ts')
  ts('ts'),
  @JsonValue('tt')
  tt('tt'),
  @JsonValue('tw')
  tw('tw'),
  @JsonValue('ty')
  ty('ty'),
  @JsonValue('ug')
  ug('ug'),
  @JsonValue('uk')
  uk('uk'),
  @JsonValue('ur')
  ur('ur'),
  @JsonValue('uz')
  uz('uz'),
  @JsonValue('ve')
  ve('ve'),
  @JsonValue('vi')
  vi('vi'),
  @JsonValue('vo')
  vo('vo'),
  @JsonValue('wa')
  wa('wa'),
  @JsonValue('wo')
  wo('wo'),
  @JsonValue('xh')
  xh('xh'),
  @JsonValue('yi')
  yi('yi'),
  @JsonValue('yo')
  yo('yo'),
  @JsonValue('za')
  za('za'),
  @JsonValue('zh')
  zh('zh'),
  @JsonValue('zu')
  zu('zu'),

  /// Default value for all unparsed values, allows backward compatibility when adding new values on the backend.
  $unknown(null);

  const UpdateClientProfileDtoLanguages(this.json);

  factory UpdateClientProfileDtoLanguages.fromJson(String json) =>
      values.firstWhere((e) => e.json == json, orElse: () => $unknown);

  final String? json;
  String toJson() {
    final value = json;
    if (value == null) {
      throw StateError(
        'Cannot convert enum value with null JSON representation to String. '
        'This usually happens for \$unknown or @JsonValue(null) entries.',
      );
    }
    return value as String;
  }

  @override
  String toString() => json?.toString() ?? super.toString();

  /// Returns all defined enum values excluding the $unknown value.
  static List<UpdateClientProfileDtoLanguages> get $valuesDefined =>
      values.where((value) => value != $unknown).toList();
}
