-- docs/04_CASES_BIDS.md §14 (stage 4.1): the only schema change of file 04.
-- Generated by `prisma migrate diff` against the dev DB; raw SQL appended
-- below.

-- AlterEnum
ALTER TYPE "notification_type" ADD VALUE 'case_updated';

-- AlterTable
ALTER TABLE "case_journal" ADD COLUMN     "attorney_id" UUID;

-- CreateIndex
CREATE INDEX "case_journal_attorney_id_created_at_idx" ON "case_journal"("attorney_id", "created_at");

-- AddForeignKey
ALTER TABLE "case_journal" ADD CONSTRAINT "case_journal_attorney_id_fkey" FOREIGN KEY ("attorney_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- Job indexes from the file-03 DB review, folded into this migration so
-- file 04 keeps a single migration:
-- CreateIndex (nightly license-expiry job)
CREATE INDEX "attorney_licenses_license_status_expires_at_idx" ON "attorney_licenses"("license_status", "expires_at");

-- CreateIndex (review-reminder job: closed cases by closed_at)
CREATE INDEX "cases_status_closed_at_idx" ON "cases"("status", "closed_at");

-- CreateIndex (reports per target / per reporter)
CREATE INDEX "reports_target_type_target_id_status_idx" ON "reports"("target_type", "target_id", "status");

-- CreateIndex
CREATE INDEX "reports_reporter_id_idx" ON "reports"("reporter_id");

-- ---------------------------------------------------------------------
-- Raw SQL (not expressible in schema.prisma)
-- ---------------------------------------------------------------------

-- §14: app_config key read by the contact-issue flow (§8.4, stage 4.5).
-- ON CONFLICT DO NOTHING: a value changed in the admin panel is kept.
INSERT INTO "app_config" ("key", "value", "updated_at")
VALUES ('contacts.suspend_after_confirmed_reports', '3'::JSONB, now())
ON CONFLICT ("key") DO NOTHING;

-- docs/02_DATABASE.md §6.2/§6.3: case_journal stays append-only for the
-- application role. No new table here; ADD COLUMN keeps table-level
-- privileges, re-asserted so the invariant is visible in this migration.
REVOKE UPDATE, DELETE ON TABLE "case_journal" FROM "lawbid_app";
GRANT SELECT, INSERT ON TABLE "case_journal" TO "lawbid_app";
